name: COVID Box

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Zaid-maker/corona-box@v0.0.1
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COUNTRY: ${{ secrets.COUNTRY }}
          GIST_ID: ${{ secrets.GIST_ID }}
